### PR TITLE
Add OIDC inputs in Values

### PR DESCRIPTION
**Pull request by tomwardill-payoneer**
Add OIDC inputs to the values.yaml, so they can be used as ENV_VARs in the Deployment.

### CODE REVIEW

**Comment by tomwardill-payoneer** [comment]
@leg100 I think I'm doing this right, my Go isn't great, so I had to guess a bit at how the command line flags became environment variables.

tbh, neither is my helm, so I might've done something silly with the secret handling :)

**Comment by leg100** [comment]
It looks good. Just be sure to run:

`make readme`: generates a new readme from the new values you've added.
`make bump`: bumps the chart version (every time a change is made the version needs to be bumped before it can be released).

You may need to install some software to get those two make tasks to run.

**Comment by tomwardill-payoneer** [comment]
@leg100 ah, thanks. Done :)

**Comment by leg100** [comment]
I got the make tasks the wrong way round: run `make readme` once again to update to badges to reflect the bumped version.

**Comment by tomwardill-payoneer** [comment]
Ah, I missed that one too. Updated again.

**Comment by leg100** [comment]
Excellent. Nice one.

**Pull request merged**
