### PR TITLE
Allow custom definitions for the caCerts volumes

### PR DESCRIPTION
**Pull request by darkevilmac**
Allows custom definition of caCerts volume, default behaviour pulls only from a configmap but this isn't ideal when used with something like cert-manager which places their generated certs in a Secret.

By default if no value is specified the previous behaviour will happen instead, keeping backwards compatibility with older versions of the chart.

### CODE REVIEW

**Comment by darkevilmac** [comment]
@leg100 if there's a procedure here for getting this merged let me know. I am running this change on my cluster now and it's working as expected.

Not super familiar with the ins and outs of helm and if there's a way to add a unit/integration test for this change.

**Comment by leg100** [comment]
@darkevilmac Thanks for the contribution.

I hope you don't mind but I've decided to turn this into opportunity to refactor the way CA certificates are specified and to make it a breaking change.

I originally implemented it pretty badly. But with this change I think the intent is clearer and there are now some sensible defaults.

Please, if you could, test the changes, using the new values:

https://github.com/leg100/otf-charts/blob/505a47f3c8a162d777a282c077da70519c9d8289/README.md#values

**Comment by darkevilmac** [comment]
I'll give it a shot and get back to you within the next 24 hours - cursory glance shows it looks correct though. In the sense that the template looks basically the same as the output of my branch with my values.yaml.

**Comment by darkevilmac** [comment]
Gave it a quick run locally and it looks like the output is effectively identical after adjusting my values to match the new spec.

**Pull request merged**
