### PR TITLE
Add support for passing extra environment variables from a Kubernetes secret

### PR DESCRIPTION
**Pull request by makelarisjr**
This PR adds support for passing extra environment variables from a Kubernetes secret.

### CODE REVIEW

**Comment by leg100** [comment]
@makelarisjr Thanks for your contribution. I don't think it is clear what value is expected in `extraEnvsFromSecret`. It looks  to be an array of maps, with a certain schema, which might easily confuse a user.

Instead, perhaps it is better to use `envFrom`, which simply loads of env vars from the named secret?

https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data

**Comment by makelarisjr** [comment]
Hey @leg100, you are right! `envFrom` will work just fine, but it may cause some problems if you want to overwrite an env var that is passed from the `env` list.
I pushed the [changes](https://github.com/leg100/otf-charts/pull/57/commits/5538afae8797e2bd7fbf49ac69906623f9ee6a9c).

**Comment by leg100** [comment]
Thanks. I've made a change to simplify it, so that the user need only specify the name of the secret.

I've also bumped the version and re-generated the readme, using:

```bash
make bump readme
```

Can you review the changes I've made and let me know if you're happy with them?

**Comment by makelarisjr** [comment]
LGTM!

**Pull request merged**
